apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-two
  namespace: go-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-two
  template:
    metadata:
      labels:
        app: service-two
    spec:
      containers:
      - name: service-two
        image: localhost:5001/go_kube_service_two:latest
        ports:
        - containerPort: 8080
