# https://taskfile.dev

version: '3'

tasks:

    ###################################################
    # Config 
    ###################################################
    start-cluster:
      desc: Start KinD cluster
      cmds:
      - bash ./bash/cluster-setup.sh
    
    apply-ingress:
      desc: Apply NginX ingress
      cmds:
      - kubectl apply -f ./manifests/config/ingress.yaml
    
    apply-config:
      desc: Apply config setup manifests
      cmds:
      - kubectl apply -f ./manifests/config/namespaces.yaml
      - kubectl apply -f ./manifests/config/secret.yaml
    
    ###################################################
    # API Build
    ###################################################
    build-api:
        desc: Build and push the docker image for backend API server
        cmds: 
        - docker build -t localhost:5001/go_kube_api_service:latest ./api
        - docker push localhost:5001/go_kube_api_service:latest

    ###################################################
    # Service Deploy
    ###################################################
    deploy-api:
        desc: Deploy api server yaml files
        cmds: 
        - kubectl apply -f ./manifests/api-service/deployment.yaml
        - kubectl apply -f ./manifests/api-service/service.yaml

    ###################################################
    # Contour Helm
    ###################################################
    deploy-contour:
        desc: Deploy Contour Ingress proxy
        cmds: 
        - helm install my-release bitnami/contour --namespace projectcontour
    deploy-routes:
        desc: Deploy Contour Ingress routes
        cmds: 
        - kubectl apply -f manifests/config/contour-ingress.yaml

    ###################################################
    # MySQL Deployment
    ###################################################
    deploy-mysql-storage:
        desc: Deploy resources for mysql db
        cmds: 
        - kubectl apply -f ./manifests/mysql/mysql-storage.yaml
    deploy-mysql:
        desc: Deploy resources for mysql db
        cmds: 
        - kubectl apply -f ./manifests/mysql/service.yaml
        - kubectl apply -f ./manifests/mysql/deployment.yaml

    ###################################################
    # Redis Deployment
    ###################################################
    deploy-redis:
        desc: Deploy resources for redis cache
        cmds: 
        - kubectl apply -f ./manifests/redis/deployment.yaml
        - kubectl apply -f ./manifests/redis/service.yaml

    ###################################################
    # MYSQL Migrator Job
    ###################################################
    build-migrator:
        desc: Build the SQL migrator job image
        cmds: 
        - docker build -t localhost:5001/go_migrator:latest ./migrations
        - docker push localhost:5001/go_migrator:latest
    deploy-migrator:
        desc: Deploy migrator job
        cmds: 
        - kubectl apply -f ./manifests/migrator/job.yaml
    newmigration:
        desc: Create a new migration file. Example - task newmigration -- add_new_cols
        cmds:
        - goose -dir ./migrations/schemas create {{.CLI_ARGS}} sql

