apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-svc
  namespace: go-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-svc
  template:
    metadata:
      labels:
        app: api-svc
    spec:
      containers:
      - name: api-svc
        image: localhost:5001/go_kube_api_service:latest
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret # our mysql-secret manifest
              key: password
        - name: MYSQL_DATABASE
          value: "go-microservices-db"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_HOST
          value: "mysql"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: ""
