apiVersion: batch/v1
kind: Job
metadata:
  name: goose-migrator
  namespace: go-microservices
spec:
  ttlSecondsAfterFinished: 120 # automatically delete job, so it can be manually deployed again if needed
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: goose-migrator
          image: localhost:5001/go_migrator:latest
          command: ["sh"] # alpine doesn't have bash  
          args:
          - -c
          - goose -dir /app/schemas -table _migrations mysql "$MYSQL_USER:$MYSQL_PASSWORD@tcp($MYSQL_HOST:$MYSQL_PORT)/$MYSQL_DATABASE?parseTime=True" up
          env:
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
          - name: MYSQL_DATABASE
            value: "go-microservices-db"
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_HOST
            value: "mysql"


