apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: go-microservices-routing
  namespace: go-microservices
spec:
  virtualhost:
    fqdn: localhost
  routes:
    - conditions:
      - prefix: /one
      pathRewritePolicy:
        replacePrefix:
        - prefix: /one
          replacement: /
      services:
        - name: service-one
          port: 80
    - conditions:
      - prefix: /two
      services:
        - name: service-two
          port: 80
      pathRewritePolicy:
        replacePrefix:
        - prefix: /two
          replacement: /