apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: go-microservices
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:7-alpine
        name: redis
        ports:
        - containerPort: 6379
